[book]
title = "tinyboot"
description = "A Rust bootloader for resource-constrained microcontrollers"
authors = ["Aaron Qian"]
src = "docs"
language = "en"

[output.html]
google-analytics = "G-G5D7KJHY31"
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/OpenServoCore/tinyboot"
edit-url-template = "https://github.com/OpenServoCore/tinyboot/edit/main/{path}"
no-section-label = true
